export type Role = "user" | "assistant" | "tool" | "system";

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = "message" | "trace";

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string;
  name?: string;
}

export type UIMediaKind = "image" | "video" | "file";

export interface UIMediaAttachment {
  kind: UIMediaKind;
  url?: string;
  name?: string;
}

export interface UIMessage {
  id: string;
  role: Role;
  content: string;
  kind?: MessageKind;
  traceKind?: "tool" | "progress";
  isStreaming?: boolean;
  createdAt: number;
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[];
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[];
  /** Signed or local UI-renderable media attachments. */
  media?: UIMediaAttachment[];
  /** Optional answer choices for a pending ask_user question. */
  buttons?: string[][];
}

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...``. */
  key: string;
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  preview: string;
}

export type ActivityStatus = "active" | "waiting" | "idle";

export interface ActivityItem {
  key: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  preview: string;
  status: ActivityStatus;
  live: boolean;
  messageCount: number;
  lastRole: string | null;
  lastText: string;
}

export type WorkStatus =
  | "scheduled"
  | "queued"
  | "running"
  | "waiting"
  | "succeeded"
  | "failed"
  | "cancelled"
  | "interrupted";

export interface WorkArtifact {
  artifact_id: string;
  task_id: string;
  step_id?: string | null;
  kind: string;
  name: string;
  mime: string;
  size_bytes: number;
  sha256: string;
  created_at: string;
  summary?: string | null;
  url?: string;
}

export interface WorkStep {
  step_id: string;
  task_id: string;
  seq_start: number;
  title: string;
  status: string;
  started_at?: string | null;
  completed_at?: string | null;
  summary?: string | null;
}

export interface WorkTask {
  task_id: string;
  scope: string;
  session_key: string;
  chat_id: string;
  title: string;
  prompt_preview: string;
  status: WorkStatus;
  mode: string;
  model: string;
  created_at: string;
  updated_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  last_seq: number;
  result_summary?: string | null;
  error?: string | null;
  artifact_count: number;
  steps?: WorkStep[];
  artifacts?: WorkArtifact[];
}

export interface WorkEventItem {
  task_id: string;
  seq: number;
  type: string;
  actor?: string | null;
  step_id?: string | null;
  created_at: string;
  payload: Record<string, unknown>;
}

export interface BootstrapResponse {
  token: string;
  ws_path: string;
  expires_in: number;
  model_name?: string | null;
}

export interface SettingsPayload {
  agent: {
    model: string;
    provider: string;
    resolved_provider: string | null;
    has_api_key: boolean;
  };
  providers: Array<{
    name: string;
    label: string;
  }>;
  runtime: {
    config_path: string;
  };
  model_runtime?: ModelRuntime;
  requires_restart: boolean;
}

export interface SettingsUpdate {
  model?: string;
  provider?: string;
}

export type ModelSwitchTarget = "qwen" | "minimax";

export interface ModelRuntime {
  status: "unknown" | "switching" | "active" | "failed" | string;
  active_model?: string | null;
  engine?: string | null;
  backend?: string | null;
  backend_port?: number | null;
  proxy_port?: number | null;
  switched_at?: string | null;
  requested_target?: string | null;
  error?: string | null;
  log_path?: string | null;
  state_source?: string | null;
}

export type ConnectionStatus =
  | "idle"
  | "connecting"
  | "open"
  | "reconnecting"
  | "closed"
  | "error";

export type InboundEvent =
  | { event: "ready"; chat_id: string; client_id: string }
  | { event: "attached"; chat_id: string }
  | {
      event: "message";
      chat_id: string;
      text: string;
      reply_to?: string;
      media?: string[];
      media_urls?: Array<{ url: string; name?: string }>;
      buttons?: string[][];
      /** Original prompt before the websocket text fallback appends buttons. */
      button_prompt?: string;
      /** Present when the frame is an agent breadcrumb (e.g. tool hint,
       * generic progress line) rather than a conversational reply. */
      kind?: "tool_hint" | "progress";
    }
  | {
      event: "delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    }
  | {
      event: "stream_end";
      chat_id: string;
      stream_id?: string;
    }
  | { event: "work.created"; task_id: string; task: WorkTask }
  | { event: "work.subscribed"; task_id: string }
  | {
      event: "work.event";
      task_id: string;
      seq: number;
      type: string;
      actor?: string | null;
      step_id?: string | null;
      created_at?: string | null;
      payload?: Record<string, unknown>;
    }
  | { event: "error"; chat_id?: string; detail?: string };

/** Base64-encoded image attached to an outbound ``message`` envelope.
 *
 * ``data_url`` must be a ``data:image/<png|jpeg|webp|gif>;base64,...`` string
 * — the server whitelists those MIME types and rejects everything else
 * (including SVG, to avoid an XSS surface). ``name`` is advisory: it's
 * preserved for the file on disk and surfaced as the placeholder label when
 * the session is replayed.
 */
export interface OutboundMedia {
  data_url: string;
  name?: string;
}

export type Outbound =
  | { type: "new_chat" }
  | { type: "attach"; chat_id: string }
  | {
      type: "message";
      chat_id: string;
      content: string;
      media?: OutboundMedia[];
    }
  | {
      type: "work.create";
      chat_id: string;
      content: string;
      mode?: "background";
      media?: OutboundMedia[];
    }
  | { type: "work.subscribe"; task_id: string; after_seq?: number }
  | { type: "work.cancel"; task_id: string }
  | { type: "work.message"; task_id: string; content: string };
